### PR TITLE
feat(rest/exportAsCSV): Add a button to export and download the json data in rest as a CSV

### PR DESCRIPTION
**Pull request by kaustavha**
This basically offers a workaround to this rather popular kibana issue
https://github.com/elastic/kibana/issues/1992
One of the people in the thread mentioned using the elasticsearch search api to get the right data then format it. 
This lets kopf do just that.

### CODE REVIEW

**Comment by lmenezes** [comment]
@kaustavha also looks good :)
can you also run grunt build/test and etc on this one?

also, if you prefer I can just merge this and to the rest myself.

thanks once more :+1:

**Comment by kaustavha** [comment]
@lmenezes So I realized the csv converter code that I hacked together wasn't that great and it'd be nice to have a more robust csv generator. Therefore I shoplifted the code from the online tool we've been using. This code isnt tested though so if you could test it/ give me some more time to test it properly, that'd be swell. 

I added the built file, and had to change a if elese statements indentation in an unrelated file to make the build pass. All tests pass.

**Comment by kaustavha** [comment]
Hey @lmenezes sorry for the delay, this should be good to land now.

**Comment by lmenezes** [comment]
@kaustavha you don't have to be sorry, I should be thanking you for helping out :)

**Pull request merged**
