### PR TITLE
Display Score explanation visually

### PR DESCRIPTION
**Pull request by gquintana**
Same as PR #305 for Elasticsearch 2.0

### CODE REVIEW

**Comment by lmenezes** [comment]
@gquintana hey, sorry again for taking so long.
I finally had time to look at this in detail, and there are a few things that I don't like so much:

- Perhaps the workflow should be different for visualising the enhanced explain. I see it more as a "visualisation" feature that can be turned on/off for a request that already has the explain flag set to true. This would allow both strategies. On top of this, perhaps if the request doesn't have the explain, pressing the "toggle" button would repeat the request with the new visualisation enabled.

- There are a few issues with the code itself, mostly lines too long, usage of double-quotes and etc. This is my fault for not having a proper CONTRIBUTE.MD. Will try to find time and create one. But running grunt build should tell you the things that are wrong.

- the new visualisation leaves the "shard" information out, and this is normally useful, since the difference in score might actually come from which shard a query was executed on

- the current look and feel still looks a bit rough sometimes, with the index/type being too big in comparison with the rest of the text.

I can either pick up your contributions and apply the changes myself, or you are also more than welcome to do it. Just let me know :)

and thanks again :)

**Comment by gquintana** [comment]
- About workflow, there 2 parts in your wish
  - Modifying the Request URL, I fear it would be too complicated because it would require to parse the URL (can you see something to do it easily?) and modify it (may be introducing errors).  Then you need to detect if the request is a candidate for enabling explanation. At the moment, I only detect whether the URL contains the keyword `explain` which is pretty easy.
  - Replacing the "Send & Show Explanation" by a  "Show Explanation" button. It would require to click twice (once on the send button, once on explain). The button could appear as soon as an explanation is found in the response. But the feature would remain hidden most of the time, no clue is given to the user about how to use it.
  - I also thought about ways to make the response more "lightweight":
    - using a tab panel component per search hit do switch between source and explanation
    - using a paging component to display search hit one per page
- Code style: sorry, I'll fix that
- Shard info: I'll add that at the top with the json-view directive
- Look'n'feel: I'll make document Id font smaller. I admit I am not very good at making things look beautiful.

**Comment by gquintana** [comment]
@lmenezes I fixed the last 3 points (code style, shard info, look and feel)

elasticsearch-kopf-explain

**Comment by lmenezes** [comment]
@gquintana thanks :)
Perhaps at some point I give it a go making the explain feature to be more part of the visualisation rather than the request, but this is already pretty useful!

**Pull request merged**
