### PR TITLE
Tweak error message to be unique, minor spelling

### PR DESCRIPTION
**Pull request by vocatan**
Big fan of KOPF - has made managing my Elasticsearch backups much easier!  Saw a minor issue in an error message when I tried deleting a repository and felt it only fair for me to commit back.

### CODE REVIEW

**Comment by lmenezes** [comment]
@vocatan hey, thanks for the corrections :)

Could you just rebase this and pull request against develop branch?

**Comment by vocatan** [comment]
Absolutely, will rebase and do so.  thanks and my apologies.

**Comment by vocatan** [comment]
I think that this is better, if not can close this out and I can resubmit.  Thank you!

**Comment by lmenezes** [comment]
@vocatan not really sure what happened there, but I get your commits duplicated. If you could just close this PR and open a new one only with the 3 commits I'd appreciate :)

**Comment by vocatan** [comment]
Yeah -sorry about that - resubmitting.

**Pull request closed without merging**
