### PR TITLE
Identify primary/replica and replica shards

### PR DESCRIPTION
**Pull request by yukideluxe**
Hola Leo!

I am trying to set up a ES cluster in my machine (just for fun and testing stuff) and this thing with shards/replicas is driving me crazy :grimacing: .

I've seen that in KOPF the difference between primary shards and replicas is very subtle (and unallocated shards always look the same). I've also seen that in the elasticsearch documentation they seem to differentiate them with P/R in front of the number (example https://www.elastic.co/guide/en/elasticsearch/guide/current/replica-shards.html) I thought about putting it in KOPF. That's how it looks.

What do you think? Does it look like too much information or like it overloads the interface?  

PS: Cuadradito pa la Juli! :heart:

### CODE REVIEW

**Comment by rcsole** [comment]
Looks nice! :smile:

**Comment by lmenezes** [comment]
@yukideluxe looks nice but... would look bad on indices wit 10+ shards. Not having the P/R makes this layout work up to 100 shards, and more than that is not so likely.
Still, I would be up for something that makes the primary/replica distinction more obvious :)

**Comment by yukideluxe** [comment]
how do you like? [](https://www.dropbox.com/s/0st7okf5h73vk0k/Screenshot%202015-07-28%2017.59.18.png?dl=1)

**Comment by yukideluxe** [comment]
I pushed some changes, I am sorry but I had to retab the styling files, I can revert that change if you want a clearer diff

**Comment by lmenezes** [comment]
sorry, I still don't like :(

**Comment by up-town-down** [comment]
Could you have like a faded P/R as the back fill image in a different colour with the number overlaid on the top?

**Pull request closed without merging**
